export const DYNAMICIMAGE = (name: string) =>
  `https://avatar.iran.liara.run/username?username=${name}`;
export const ChatListDummy = [
  {
    id: 1,
    name: "Alex Linderson",
    message: "How are you today?",
    unread: 2,
    time: "2 min ago",
    image: DYNAMICIMAGE("Alex Linderson"),
  },
  {
    id: 2,
    name: "Emily Carter",
    message: "Let's catch up later.",
    unread: 1,
    time: "10 min ago",
    image: DYNAMICIMAGE("Emily Carter"),
  },
  {
    id: 3,
    name: "Michael Brown",
    message: "Where are you?",
    unread: 0,
    time: "30 min ago",
    image: DYNAMICIMAGE("Michael Brown"),
  },
  {
    id: 4,
    name: "Sophia Taylor",
    message: "Call me when you're free.",
    unread: 3,
    time: "1 hour ago",
    image: DYNAMICIMAGE("Sophia Taylor"),
  },
  {
    id: 5,
    name: "James Anderson",
    message: "I'll be there soon.",
    unread: 0,
    time: "2 hours ago",
    image: DYNAMICIMAGE("James Anderson"),
  },
  {
    id: 6,
    name: "Olivia Martinez",
    message: "Can you send the files?",
    unread: 1,
    time: "3 hours ago",
    image: DYNAMICIMAGE("Olivia Martinez"),
  },
  {
    id: 7,
    name: "Liam Johnson",
    message: "Thank you!",
    unread: 0,
    time: "5 hours ago",
    image: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 8,
    name: "Ava Williams",
    message: "See you tomorrow.",
    unread: 2,
    time: "7 hours ago",
    image: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 9,
    name: "William Jones",
    message: "Can we reschedule?",
    unread: 1,
    time: "10 hours ago",
    image: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 10,
    name: "Isabella Rodriguez",
    message: "Happy Birthday!",
    unread: 0,
    time: "12 hours ago",
    image: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 11,
    name: "Elijah Davis",
    message: "I'm on my way.",
    unread: 0,
    time: "15 hours ago",
    image: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 12,
    name: "Mia Wilson",
    message: "Thanks for your help.",
    unread: 1,
    time: "18 hours ago",
    image: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 13,
    name: "Noah Garcia",
    message: "See you at the meeting.",
    unread: 0,
    time: "21 hours ago",
    image: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    id: 14,
    name: "Charlotte Lee",
    message: "Good night!",
    unread: 3,
    time: "1 day ago",
    image: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    id: 15,
    name: "Lucas White",
    message: "Let's discuss this tomorrow.",
    unread: 0,
    time: "2 days ago",
    image: "https://randomuser.me/api/portraits/men/15.jpg",
  },
];
